# Dockerfile.mlflow
FROM python:3.11-slim

# Install MLflow, PostgreSQL, and optional S3 artifact-store dependencies
RUN pip install --no-cache-dir mlflow[extras] psycopg2-binary boto3

# Create working directory
WORKDIR /mlflow
VOLUME /mlflow

# Expose port
EXPOSE 5000

# Default command
CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///mlflow.db", \
     "--artifacts-destination", "/mlflow/artifacts", \
     "--serve-artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--cors-allowed-origins", "*"]
