# Dockerfile.mlflow
FROM python:3.11-slim

# Install MLflow and dependencies
RUN pip install --no-cache-dir mlflow[extras]

# Create working directory
WORKDIR /mlflow
VOLUME /mlflow

# Expose port
EXPOSE 5000

# Default command
CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///mlflow.db", \
     "--default-artifact-root", "/mlflow/artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--cors-allowed-origins", "*" \
     "--server-artifacts"]
