apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-backend" .Release.Name }}
  labels:
    app: {{ printf "%s-backend" .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ printf "%s-backend" .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-backend" .Release.Name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {{ toYaml .Values.resources | nindent 10 }}
